// storysell-shopify-app/src/lib/fakeApi/fakeProductApi.ts
import { Product } from "../../types/product.types";

const fakeProducts: Product[] = [
  // Coleção Summer Collection (c1)
  {
    id: "p1",
    title: "Tênis Vermelho",
    description: "Confortável tênis vermelho para corrida",
    price: 49.9,
    images: ["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p2",
    title: "Chapéu Verde",
    description: "Chapéu casual de algodão",
    price: 19.9,
    images: ["https://images.pexels.com/photos/936118/pexels-photo-936118.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p3",
    title: "Tênis Preto",
    description: "Tênis preto moderno para uso diário",
    price: 59.9,
    images: ["https://images.pexels.com/photos/19090/pexels-photo.jpg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p4",
    title: "Tênis de Corrida",
    description: "Tênis leve para corrida",
    price: 59.9,
    images: ["https://images.pexels.com/photos/19090/pexels-photo.jpg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p5",
    title: "Tênis Casual",
    description: "Confortável tênis casual",
    price: 54.9,
    images: ["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p6",
    title: "Sandálias Laranja",
    description: "Sandálias leves para verão",
    price: 39.9,
    images: ["https://pixabay.com/get/g1a7e8495c6cf0d124af25e4b.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p7",
    title: "Regata Azul",
    description: "Regata confortável para dias quentes",
    price: 19.9,
    images: ["https://pixabay.com/get/g7f63a7f21d76f.jpeg"],
    available: true,
    collectionId: "c1",
  },

  // Coleção Winter Collection (c2)
  {
    id: "p8",
    title: "Jaqueta Azul",
    description: "Jaqueta de inverno estilosa",
    price: 89.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p9",
    title: "Jeans Azul",
    description: "Clássico jeans azul",
    price: 69.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p10",
    title: "Casaco de Inverno",
    description: "Casaco de inverno quente e estiloso",
    price: 129.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p11",
    title: "Gorro Cinza",
    description: "Gorro de lã para inverno",
    price: 15.9,
    images: ["https://pixabay.com/get/gd8d3e6b0f07c20d0a.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p12",
    title: "Luvas Pretas",
    description: "Luvas de couro para frio intenso",
    price: 29.9,
    images: ["https://pixabay.com/get/gc1a3f29b5d2d9e.jpeg"],
    available: true,
    collectionId: "c2",
  },
  // Coleção Accessories (c3)
  {
    id: "p13",
    title: "Carteira de Couro",
    description: "Carteira de couro legítimo",
    price: 39.9,
    images: ["https://images.pexels.com/photos/279791/pexels-photo-279791.jpeg"],
    available: true,
    collectionId: "c3",
  },
  {
    id: "p14",
    title: "Cinto de Couro",
    description: "Cinto de couro de alta qualidade",
    price: 29.9,
    images: ["https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg"],
    available: true,
    collectionId: "c3",
  },

  // Coleção Footwear (c4)
  {
    id: "p15",
    title: "Sapato Social Preto",
    description: "Sapato social elegante para trabalho",
    price: 89.9,
    images: ["https://pixabay.com/get/g3f5f1e45c9f.jpeg"],
    available: true,
    collectionId: "c4",
  },
  {
    id: "p16",
    title: "Mocassim Marrom",
    description: "Mocassim confortável de couro",
    price: 79.9,
    images: ["https://pixabay.com/get/g4d9e9f2b7a6.jpeg"],
    available: true,
    collectionId: "c4",
  },

  // Coleção T-Shirts (c5)
  {
    id: "p17",
    title: "Camiseta Amarela",
    description: "Camiseta de algodão amarela vibrante",
    price: 25.0,
    images: ["https://images.pexels.com/photos/1005019/pexels-photo-1005019.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p18",
    title: "Camisa Branca",
    description: "Camisa branca formal para escritório",
    price: 34.9,
    images: ["https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p19",
    title: "Gravata de Seda",
    description: "Luxuosa gravata de seda",
    price: 29.9,
    images: ["https://images.pexels.com/photos/230842/pexels-photo-230842.jpeg"],
    available: true,
    collectionId: "c5",
  },
  // Coleção Jackets (c6)
  {
    id: "p20",
    title: "Óculos de Sol",
    description: "Óculos de sol modernos para o verão",
    price: 24.9,
    images: ["https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p21",
    title: "Cachecol",
    description: "Cachecol macio de lã",
    price: 19.9,
    images: ["https://images.pexels.com/photos/374882/pexels-photo-374882.jpeg"],
    available: true,
    collectionId: "c6",
  },

  // Coleção Bags (c7)
  {
    id: "p22",
    title: "Mochila",
    description: "Mochila durável para viagens",
    price: 79.9,
    images: ["https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p23",
    title: "Bolsa de Couro",
    description: "Elegante bolsa de couro para trabalho",
    price: 99.9,
    images: ["https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg"],
    available: true,
    collectionId: "c7",
  },

  // Coleção Hats (c8)
  {
    id: "p24",
    title: "Gorro",
    description: "Gorro de algodão quente para inverno",
    price: 15.9,
    images: ["https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg"],
    available: true,
    collectionId: "c8",
  },

  // Coleção Watches (c9)
  {
    id: "p25",
    title: "Relógio Esportivo",
    description: "Relógio digital esportivo",
    price: 49.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },

  // Coleção Special Collection (c10)
  {
    id: "p26",
    title: "Anel de Ouro",
    description: "Elegante anel de ouro",
    price: 59.9,
    images: ["https://images.pexels.com/photos/128867/pexels-photo-128867.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p27",
    title: "Pulseira de Prata",
    description: "Pulseira de prata fina e elegante",
    price: 39.9,
    images: ["https://pixabay.com/get/gd1234567890.jpeg"], // exemplo Pixabay
    available: true,
    collectionId: "c10",
  },
  {
    id: "p28",
    title: "Colar de Pérolas",
    description: "Colar de pérolas delicado",
    price: 89.9,
    images: ["https://pixabay.com/get/gd0987654321.jpeg"], // exemplo Pixabay
    available: true,
    collectionId: "c10",
  },
  {
    id: "p29",
    title: "Brincos de Ouro",
    description: "Brincos de ouro elegantes",
    price: 49.9,
    images: ["https://pixabay.com/get/gd1122334455.jpeg"], // exemplo Pixabay
    available: true,
    collectionId: "c10",
  },
  {
    id: "p30",
    title: "Gravata Luxuosa",
    description: "Gravata luxuosa para ocasiões especiais",
    price: 59.9,
    images: ["https://pixabay.com/get/gd6677889900.jpeg"], // exemplo Pixabay
    available: true,
    collectionId: "c10",
  },
  // Coleção T-Shirts (c5)
  {
    id: "p31",
    title: "Camiseta Branca",
    description: "Camiseta básica branca de algodão",
    price: 24.9,
    images: ["https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p32",
    title: "Camiseta Preta",
    description: "Camiseta preta confortável",
    price: 24.9,
    images: ["https://images.pexels.com/photos/1005007/pexels-photo-1005007.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p33",
    title: "Camiseta Vermelha",
    description: "Camiseta vermelha vibrante",
    price: 24.9,
    images: ["https://images.pexels.com/photos/1005012/pexels-photo-1005012.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p34",
    title: "Camiseta Azul",
    description: "Camiseta azul casual",
    price: 24.9,
    images: ["https://images.pexels.com/photos/1005015/pexels-photo-1005015.jpeg"],
    available: true,
    collectionId: "c5",
  },

  // Coleção Jackets (c6)
  {
    id: "p35",
    title: "Jaqueta de Couro Marrom",
    description: "Jaqueta de couro legítimo marrom",
    price: 129.9,
    images: ["https://pixabay.com/get/gd5566778899.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p36",
    title: "Jaqueta Jeans",
    description: "Jaqueta jeans estilosa",
    price: 99.9,
    images: ["https://images.pexels.com/photos/428334/pexels-photo-428334.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p37",
    title: "Blusão Cinza",
    description: "Blusão de moletom cinza confortável",
    price: 79.9,
    images: ["https://images.pexels.com/photos/936119/pexels-photo-936119.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p38",
    title: "Casaco de Lã",
    description: "Casaco de lã elegante",
    price: 149.9,
    images: ["https://pixabay.com/get/gd6677885566.jpeg"],
    available: true,
    collectionId: "c6",
  },

  // Coleção Accessories (c3)
  {
    id: "p39",
    title: "Cinto Marrom",
    description: "Cinto de couro marrom de alta qualidade",
    price: 29.9,
    images: ["https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg"],
    available: true,
    collectionId: "c3",
  },
  {
    id: "p40",
    title: "Carteira Preta",
    description: "Carteira de couro preta elegante",
    price: 39.9,
    images: ["https://images.pexels.com/photos/279791/pexels-photo-279791.jpeg"],
    available: true,
    collectionId: "c3",
  },
  // Coleção Accessories (c3) continua
  {
    id: "p41",
    title: "Chapéu Preto",
    description: "Chapéu casual de algodão preto",
    price: 19.9,
    images: ["https://images.pexels.com/photos/936118/pexels-photo-936118.jpeg"],
    available: true,
    collectionId: "c3",
  },
  {
    id: "p42",
    title: "Óculos de Sol Redondo",
    description: "Óculos de sol estilo vintage",
    price: 29.9,
    images: ["https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg"],
    available: true,
    collectionId: "c3",
  },

  // Coleção Footwear (c4)
  {
    id: "p43",
    title: "Tênis Branco",
    description: "Tênis casual branco confortável",
    price: 59.9,
    images: ["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg"],
    available: true,
    collectionId: "c4",
  },
  {
    id: "p44",
    title: "Botas Pretas",
    description: "Botas elegantes para inverno",
    price: 99.9,
    images: ["https://pixabay.com/get/gf6677889001.jpeg"],
    available: true,
    collectionId: "c4",
  },
  {
    id: "p45",
    title: "Sandálias Marrom",
    description: "Sandálias leves e confortáveis",
    price: 39.9,
    images: ["https://pixabay.com/get/gd5566778899.jpeg"],
    available: true,
    collectionId: "c4",
  },
  {
    id: "p46",
    title: "Sapato Social Preto",
    description: "Sapato social clássico para escritório",
    price: 129.9,
    images: ["https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg"],
    available: true,
    collectionId: "c4",
  },
  {
    id: "p47",
    title: "Tênis Esportivo Azul",
    description: "Tênis esportivo para corrida e treino",
    price: 69.9,
    images: ["https://images.pexels.com/photos/19090/pexels-photo.jpg"],
    available: true,
    collectionId: "c4",
  },

  // Coleção Bags (c7)
  {
    id: "p48",
    title: "Mochila de Couro",
    description: "Mochila elegante de couro para trabalho",
    price: 89.9,
    images: ["https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p49",
    title: "Bolsa Tote",
    description: "Bolsa tote espaçosa para o dia a dia",
    price: 79.9,
    images: ["https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p50",
    title: "Pochete Preta",
    description: "Pochete compacta e prática",
    price: 49.9,
    images: ["https://pixabay.com/get/gd9988776655.jpeg"],
    available: true,
    collectionId: "c7",
  },
  // Coleção Hats (c8)
  {
    id: "p51",
    title: "Gorro Azul",
    description: "Gorro de lã macio para inverno",
    price: 14.9,
    images: ["https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg"],
    available: true,
    collectionId: "c8",
  },
  {
    id: "p52",
    title: "Chapéu Panamá",
    description: "Chapéu Panamá elegante para verão",
    price: 29.9,
    images: ["https://pixabay.com/get/gf3344556677.jpeg"],
    available: true,
    collectionId: "c8",
  },
  {
    id: "p53",
    title: "Boné Preto",
    description: "Boné casual para o dia a dia",
    price: 19.9,
    images: ["https://images.pexels.com/photos/936118/pexels-photo-936118.jpeg"],
    available: true,
    collectionId: "c8",
  },

  // Coleção Watches (c9)
  {
    id: "p54",
    title: "Relógio Analógico",
    description: "Relógio clássico com pulseira de couro",
    price: 149.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },
  {
    id: "p55",
    title: "Relógio Digital",
    description: "Relógio digital esportivo",
    price: 49.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },
  {
    id: "p56",
    title: "Relógio Minimalista",
    description: "Relógio elegante e minimalista",
    price: 99.9,
    images: ["https://pixabay.com/get/gf2233445566.jpeg"],
    available: true,
    collectionId: "c9",
  },

  // Coleção Special Collection (c10)
  {
    id: "p57",
    title: "Anel de Ouro",
    description: "Anel sofisticado em ouro 18k",
    price: 299.9,
    images: ["https://images.pexels.com/photos/128867/pexels-photo-128867.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p58",
    title: "Gravata de Seda Vermelha",
    description: "Gravata de seda premium",
    price: 39.9,
    images: ["https://images.pexels.com/photos/230842/pexels-photo-230842.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p59",
    title: "Pulseira de Couro",
    description: "Pulseira elegante de couro",
    price: 49.9,
    images: ["https://pixabay.com/get/gf1122334455.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p60",
    title: "Brincos de Prata",
    description: "Brincos delicados em prata",
    price: 69.9,
    images: ["https://pixabay.com/get/gf6677889900.jpeg"],
    available: true,
    collectionId: "c10",
  },
  // Coleção Bags (c7)
  {
    id: "p61",
    title: "Mochila Executiva",
    description: "Mochila de couro resistente para trabalho",
    price: 129.9,
    images: ["https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p62",
    title: "Bolsa de Ombro",
    description: "Bolsa de ombro elegante e prática",
    price: 89.9,
    images: ["https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p63",
    title: "Clutch Feminina",
    description: "Clutch pequena para eventos sociais",
    price: 59.9,
    images: ["https://pixabay.com/get/gf4455667788.jpeg"],
    available: true,
    collectionId: "c7",
  },

  // Coleção T-Shirts (c5)
  {
    id: "p64",
    title: "Camiseta Preta",
    description: "Camiseta básica preta de algodão",
    price: 29.9,
    images: ["https://images.pexels.com/photos/1005019/pexels-photo-1005019.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p65",
    title: "Camiseta Branca",
    description: "Camiseta clássica branca",
    price: 29.9,
    images: ["https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p66",
    title: "Camiseta Listrada",
    description: "Camiseta casual listrada",
    price: 34.9,
    images: ["https://pixabay.com/get/gf9988776655.jpeg"],
    available: true,
    collectionId: "c5",
  },

  // Coleção Jackets (c6)
  {
    id: "p67",
    title: "Jaqueta de Couro",
    description: "Jaqueta de couro premium",
    price: 149.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p68",
    title: "Casaco de Lã",
    description: "Casaco de lã quente para inverno",
    price: 129.9,
    images: ["https://pixabay.com/get/gf5566778899.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p69",
    title: "Colete Jeans",
    description: "Colete jeans estiloso",
    price: 89.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p70",
    title: "Capa de Chuva",
    description: "Capa de chuva leve e prática",
    price: 49.9,
    images: ["https://pixabay.com/get/gf3344556677.jpeg"],
    available: true,
    collectionId: "c6",
  },
  // Coleção Hats (c8)
  {
    id: "p71",
    title: "Boné Azul",
    description: "Boné casual de algodão",
    price: 19.9,
    images: ["https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg"],
    available: true,
    collectionId: "c8",
  },
  {
    id: "p72",
    title: "Chapéu Panamá",
    description: "Chapéu de palha elegante para verão",
    price: 34.9,
    images: ["https://pixabay.com/get/gf7788990011.jpeg"],
    available: true,
    collectionId: "c8",
  },
  {
    id: "p73",
    title: "Gorro Vermelho",
    description: "Gorro de lã para dias frios",
    price: 14.9,
    images: ["https://pixabay.com/get/gf1122334455.jpeg"],
    available: true,
    collectionId: "c8",
  },

  // Coleção Watches (c9)
  {
    id: "p74",
    title: "Relógio Casual",
    description: "Relógio para uso diário",
    price: 49.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },
  {
    id: "p75",
    title: "Relógio Esportivo",
    description: "Relógio digital esportivo para treino",
    price: 59.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },
  {
    id: "p76",
    title: "Relógio de Luxo",
    description: "Relógio elegante com pulseira de couro",
    price: 149.9,
    images: ["https://pixabay.com/get/gf6677889900.jpeg"],
    available: true,
    collectionId: "c9",
  },

  // Coleção Special Collection (c10)
  {
    id: "p77",
    title: "Anel de Ouro",
    description: "Anel elegante de ouro 18k",
    price: 59.9,
    images: ["https://images.pexels.com/photos/128867/pexels-photo-128867.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p78",
    title: "Brincos de Prata",
    description: "Brincos sofisticados de prata",
    price: 49.9,
    images: ["https://pixabay.com/get/gf2233445566.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p79",
    title: "Colar de Pérolas",
    description: "Colar elegante de pérolas naturais",
    price: 99.9,
    images: ["https://pixabay.com/get/gf3344556677.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p80",
    title: "Gravata de Seda",
    description: "Luxuosa gravata de seda",
    price: 29.9,
    images: ["https://images.pexels.com/photos/230842/pexels-photo-230842.jpeg"],
    available: true,
    collectionId: "c10",
  },
];

export const getProducts = async (): Promise<Product[]> => {
  return new Promise((resolve) => setTimeout(() => resolve(fakeProducts), 500));
};

export const getProductById = async (id: string): Promise<Product> => {
  const product = fakeProducts.find((p) => p.id === id);
  if (!product) throw new Error("Produto não encontrado");
  return new Promise((resolve) => setTimeout(() => resolve(product), 500));
};
