// storysell-shopify-app/src/lib/fakeApi/fakeProductApi.ts
import { Product } from "../../types/product.types";

const fakeProducts: Product[] = [
  {
    id: "p1",
    title: "Red Shoes",
    description: "Comfortable red running shoes",
    price: 49.9,
    images: ["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p2",
    title: "Blue Jacket",
    description: "Stylish winter jacket",
    price: 89.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p3",
    title: "Green Hat",
    description: "Casual cotton hat",
    price: 19.9,
    images: ["https://images.pexels.com/photos/936118/pexels-photo-936118.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p4",
    title: "Yellow T-Shirt",
    description: "Bright yellow cotton t-shirt",
    price: 25.0,
    images: ["https://images.pexels.com/photos/1005019/pexels-photo-1005019.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p5",
    title: "Leather Wallet",
    description: "Genuine leather wallet",
    price: 39.9,
    images: ["https://images.pexels.com/photos/279791/pexels-photo-279791.jpeg"],
    available: true,
    collectionId: "c3",
  },
  {
    id: "p6",
    title: "Black Sneakers",
    description: "Modern black sneakers for daily use",
    price: 59.9,
    images: ["https://images.pexels.com/photos/19090/pexels-photo.jpg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p7",
    title: "Denim Jeans",
    description: "Classic blue denim jeans",
    price: 69.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p8",
    title: "Leather Belt",
    description: "High-quality leather belt",
    price: 29.9,
    images: ["https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg"],
    available: true,
    collectionId: "c3",
  },
  {
    id: "p9",
    title: "White Shirt",
    description: "Formal white shirt for office",
    price: 34.9,
    images: ["https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg"],
    available: true,
    collectionId: "c5",
  },
  {
    id: "p10",
    title: "Sunglasses",
    description: "Trendy summer sunglasses",
    price: 24.9,
    images: ["https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p11",
    title: "Backpack",
    description: "Durable backpack for travel",
    price: 79.9,
    images: ["https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p12",
    title: "Running Shoes",
    description: "Lightweight running shoes",
    price: 59.9,
    images: ["https://images.pexels.com/photos/19090/pexels-photo.jpg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p13",
    title: "Beanie Hat",
    description: "Warm cotton beanie for winter",
    price: 15.9,
    images: ["https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg"],
    available: true,
    collectionId: "c8",
  },
  {
    id: "p14",
    title: "Sports Watch",
    description: "Digital sports watch",
    price: 49.9,
    images: ["https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg"],
    available: true,
    collectionId: "c9",
  },
  {
    id: "p15",
    title: "Leather Bag",
    description: "Elegant leather bag for work",
    price: 99.9,
    images: ["https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg"],
    available: true,
    collectionId: "c7",
  },
  {
    id: "p16",
    title: "Casual Sneakers",
    description: "Comfortable casual sneakers",
    price: 54.9,
    images: ["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg"],
    available: true,
    collectionId: "c1",
  },
  {
    id: "p17",
    title: "Winter Coat",
    description: "Warm and stylish winter coat",
    price: 129.9,
    images: ["https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg"],
    available: true,
    collectionId: "c2",
  },
  {
    id: "p18",
    title: "Scarf",
    description: "Soft wool scarf",
    price: 19.9,
    images: ["https://images.pexels.com/photos/374882/pexels-photo-374882.jpeg"],
    available: true,
    collectionId: "c6",
  },
  {
    id: "p19",
    title: "Gold Ring",
    description: "Elegant gold ring",
    price: 59.9,
    images: ["https://images.pexels.com/photos/128867/pexels-photo-128867.jpeg"],
    available: true,
    collectionId: "c10",
  },
  {
    id: "p20",
    title: "Silk Tie",
    description: "Luxury silk tie",
    price: 29.9,
    images: ["https://images.pexels.com/photos/230842/pexels-photo-230842.jpeg"],
    available: true,
    collectionId: "c5",
  },
];

export const getProducts = async (): Promise<Product[]> => {
  return new Promise((resolve) => setTimeout(() => resolve(fakeProducts), 500));
};

export const getProductById = async (id: string): Promise<Product> => {
  const product = fakeProducts.find((p) => p.id === id);
  if (!product) throw new Error("Product not found");
  return new Promise((resolve) => setTimeout(() => resolve(product), 500));
};
